"""4Migration

Revision ID: ef55fa124d29
Revises: f60ca9a6c271
Create Date: 2018-09-15 16:23:31.730797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef55fa124d29'
down_revision = 'f60ca9a6c271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_blogs_email'), 'blogs', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blogs_email'), table_name='blogs')
    op.drop_column('blogs', 'email')
    # ### end Alembic commands ###
